### ISSUE TITLE
Specify the loading/usage rate of asset 

### ISSUE THREAD

**Issue by tanyayez** [bulgarian-open-source/airport#31]
The typical loading/usage rate is recorded and captured for the Asset as the percentage from 0% to 100%

**Comment by ipopovych** [comment]
@tanyayez Please make sure that loading/usage rate has correct boundaries (i.e. 0..100). 

For now, we decided to revert your merge. You can work on that on your branch until the issue is resolved. 

Also, please make sure to assign your pull request to someone **before** integrating it. Merges without reviewers approve are not desired.

**Comment by ipopovych** [comment]
@livochka PTAL

**Comment by livochka** [comment]
@tanyayez @ipopovych fixed and covered by tests. UI implemented.
